### ISSUE TITLE
Expose wallet address error details

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/filecoin-station#145]
From https://github.com/filecoin-project/filecoin-station/pull/75#discussion_r977422069:

> I think that showing the validation error might be too technical and it should be wrapped into a proper message

> I have mixed feelings. On one hand, I agree that most users don't care about a detailed technical explanation. On the other hand, sometimes the technical explanation could be helpful - e.g. when the address has incorrect length, perhaps because the user omitted some of the characters.

> I am proposing to show a generic message followed with a question-mark icon (?), and when the user clicks or hovers on the icon, then show additional error details.

<img width="651" alt="Screenshot 2022-09-23 at 09 44 27" src="https://user-images.githubusercontent.com/10247/191913661-a6a1d593-7326-4dbb-9a14-754895d004f9.png">

<img width="634" alt="Screenshot 2022-09-23 at 11 11 21" src="https://user-images.githubusercontent.com/10247/191928610-95004437-ab0f-478f-b77f-a73c3173f3f1.png">

**Comment by jopedroliveira** [comment]
Thinking about if technical details should or should not be displayed, it would be interesting to research from the UX perspective whether the user wants or needs to see what's the root cause of the error.  
Maybe that detail is not that important for the end-user. Not even sure if that info is relevant for tracking. 

In the meantime:
 #194 replaces the detailed message with a generic one
 #193 adds a tooltip on hover with the detailed message, but design was not validated


I suggest keeping this discussion open and looking forward to a Ux scan over this.
