### ISSUE TITLE
Cannot open GUI after restarting Computer

### ISSUE THREAD

**Issue by walkerlj0** [filecoin-station/filecoin-station#266]
Started Filecoin station- amazing (can't wait to do this with Launchpad residents)

Tried just as an experiment to see what would happen if I restarted my comp. It seems as though Filecoin station has processes running, but I cannot open the GUI from the menu bar or Applications folder.

And also now somehow the icon is stuck on screen:
<img width="1910" alt="Screen Shot 2022-11-08 at 2 27 05 PM" src="https://user-images.githubusercontent.com/66978602/200668325-2093a401-afad-4f8d-b5ca-0941693be188.png">

What is the process/ application name so I can `killall` in terminal?

MacOS Monterey V12.6, Apple M1 Pro chip

**Comment by bajtos** [comment]
Hi @walkerlj0, thank you for reporting the issue to us!

> Tried just as an experiment to see what would happen if I restarted my comp. It seems as though Filecoin station has processes running, but I cannot open the GUI from the menu bar or Applications folder.

That's very weird 🤔

The Station intentionally starts in the background, showing only the menubar icon. However, it should be possible to open the GUI.

Maybe there is a bug in our implementation of "Start at Login". Any ideas, @juliangruber?

> What is the process/ application name so I can `killall` in terminal?

Before going the killall route, could you please check if the Station's Tray/Menubar menu works for you? I can see the Station logo in your top menubar:

![tray-screenshot](https://user-images.githubusercontent.com/1140553/200774847-ef52a57f-d773-4987-9a0d-54cd24703215.png)

When you click the icon, you should get a menu with an option to quit the app.

Screenshot from my computer:

<img width="285" alt="Screenshot 2022-11-09 at 09 13 52" src="https://user-images.githubusercontent.com/1140553/200775177-78fa64e3-bde8-4943-8e93-1719885148ef.png">

What happens when you click on "Quit Station"?

In case that does not work - here is the command to kill the Station from the terminal. 

```
killall "Filecoin Station"
```

The process name contains a space character we need to escape to prevent the shell from splitting the name into two arguments. One option is to enclose the process name in quotes.

**Comment by walkerlj0** [comment]
Thanks @bajtos , I was able to open the GUI with the icon in the top tray/menubar, thanks!

**Comment by juliangruber** [comment]
Thank you for reporting @walkerlj0! We have a potential improvement in https://github.com/filecoin-station/filecoin-station/pull/274, where we make it so Station shows its UI when you try to open it twice (although it was already open, hidden in the tray).
